BlueFlame/BlueFlame/urls.py
# urlpatterns 필수 사항
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path
from FestivalApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),

    path('timeline', views.timeLine, name='timeline'),
    path('booth2', views.booth2, name='booth2'),

    path('booth/<int:day>', views.booth, name="booth"),

    path('pub/<int:pub_id>', views.pubDetail, name="pub"),
    path('club/<int:club_id>', views.clubDetail, name="club"),

    path('aboutus', views.aboutUs, name="aboutus" ),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

BlueFlame/FestivalApp/models.py
from django.db import models

class Club(models.Model):
    name = models.CharField("NAME", max_length=50) # 동아리 이름
    description = models.CharField("DESCRIPTION", max_length=100, blank=True, null= True) # 동아리 요약(해쉬태그 형식)
    content = models.TextField("CONTENT", blank=True, null=True) # 동아리 소개글
    information = models.TextField("INFORMATION", blank=True, null=True) # 동아리 부스 정보
    location = models.CharField("LOCATION", max_length=50) # 동아리 부스 위치(grassField, )
    contact = models.CharField("CONTACT", max_length=50, blank=True, null=True) # 동아리 인스타 주소
    image = models.ImageField("IMAGE", upload_to="club/", blank=True, null=True) # 동아리 이미지
    date= models.IntegerField("DATE") # 부스 운영 날짜
    belong = models.CharField("BELONG", max_length=50, blank=True, null=True) # 주점 소속
    distinct=models.IntegerField("DIS", blank=True, null=True)
    # 0: 수, 1: 목, 2: 금
    
    class Meta:
        verbose_name = "Club"
        verbose_name_plural = "Clubs"

    def __str__(self):
        return self.name


class Pub(models.Model):
    name = models.CharField("NAME", max_length=50) # 주점 이름
    description = models.CharField("DESCRIPTION", max_length=100, blank=True, null= True) # 주점 요약(해쉬태그 형식)
    content = models.TextField("CONTENT", blank=True, null=True) # 주점 소개글
    belong = models.CharField("BELONG", max_length=50) # 주점 소속
    location = models.CharField("LOCATION", max_length=50) # 주점 부스 위치
    contact = models.CharField("CONTACT", max_length=50, blank=True, null=True) # 주점 인스타 주소
    image = models.ImageField("IMAGE", upload_to="pub/", blank=True, null=True) # 주점 이미지
    date= models.IntegerField("DATE") # 부스 운영 날짜
    distinct=models.IntegerField("DIS", blank=True, null=True)
    # 0: 수, 1: 목, 2: 금
    

    class Meta:
        verbose_name = "Pub"
        verbose_name_plural = "Pubs"

    def __str__(self):
        return self.name
    
class Menu(models.Model):
    pub = models.ForeignKey(Pub, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField("NAME", max_length=50)
    decription = models.CharField("DESCRIPTION", max_length=100, blank=True, null= True)
    price = models.CharField("PRICE", max_length=50, blank=True, null= True)

    def __str__(self):
        return self.name

BlueFlame/FestivalApp/views.py
from django.shortcuts import get_object_or_404, render
from .models import Pub, Club

def home(request):
    return render(request, 'main.html')

def timeLine(request):
    return render(request, 'timeline2.html')

def booth2(request):
    return render(request, 'booth(Day1).html')

def booth(request, day):
    if day == 0:
        template ="booth(Day1).html"
    elif day == 1:
        template ="booth(Day2).html"
    else:
        template="booth(Day3).html"
        day = 1
    pubs = Pub.objects.filter(date = day)
    clubs = Club.objects.filter(date = day)
    return render(request, template, {'pubs':pubs, 'clubs':clubs})

def pubDetail(request, pub_id):
    pub = get_object_or_404(Pub, pk = pub_id)
    return render(request, 'pub.html', {'pub':pub})

def clubDetail(request, club_id):
    club = get_object_or_404(Club, pk = club_id)
    return render(request, 'club.html', {'club':club})

def aboutUs(request):
    return render(request, 'aboutus.html')

BlueFlame/FestivalApp/templates/aboutus.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.0/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/aboutus.css' %}">
    <link rel="stylesheet" href="{% static 'css/default.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <title>Document</title>
</head>
<body>
    <nav class="navbar fixed-top">
        <input type="checkbox" id="icon">
    <label for="icon">  <!--label은 인라인 스타일-->
        <span></span>
        <span></span>
        <span></span>
    </label>
    <div id="header">
        <img src="{% static 'img/Menu.png' %}" style="height: 3vh; margin-top: 27px; margin-left: 30px;" >
        <div class="line"></div>
        <ul class="menu_item" style="margin-left: 30px;">
            <li>
                <img src="{% static 'img/Vector.png' %}" style="height: 1.5vh;">
                <a href="{% url 'timeline' %}">타임 테이블</a>
            </li>
            <li>
                <img src="{% static 'img/Vector.png' %}" style="height: 1.5vh;">
                <a href="{% url 'booth' 0 %}">부스 안내</a>
            </li>
            <li>
                <img src="{% static 'img/Vector.png' %}" style="height: 1.5vh;">
                <a href="{% url 'aboutus' %}">About us</a>
            </li>
            <li class="menu_li">
                <img src="{% static 'img/Vector.png' %}" style="height: 1.5vh;">
                <a href="{% url 'home' %}">Home</a>
            </li>
        </ul>
    </div>
    </nav>
    <div class="aboutus-container">
        <div class="blank-box"></div>
        <div class="aboutus-title">About us</div>
        <nav class="aboutus-nav">
            <div id="nav1" onclick="changeToLikelion()">멋쟁이 사자처럼</div>
            <div id="nav2" onclick="changeToCreator()">Developer</div>
        </nav>

        <!-- 멋쟁이 사자처럼 페이지 -->
        <div id="likelion-page">
            <img id="likelion-logo-img" src="{% static 'img/logo.png' %}">
            <div id="likelion-explain">
                멋쟁이사자처럼은 전국 61개의 대학이 모인<br>
                전국 최대 규모 개발/창업 동아리입니다.<br>
                <br>
                한성대학교 멋쟁이사자처럼은 현재 약 30명의 부원이 활동하고 있으며,<br>
                일상의 불편함에서얻은 아이디어를 통해<br>
                소소하고도 확실한 편리를 만들어내는 서비스를<br>
                직접 구현할 수 있도록 교육하고 있습니다.<br><br>

                간만에 찾아온 봄 축제를 학우분들이 보다 편하고 즐겁게<br>
                즐기시길 바라는 마음으로 본 사이트를 기획하게 되었습니다.<br><br>

                감사합니다 :&#41;
            </div>
            <img id="likelion-all" src="{% static 'img/all.png' %}">

            <a href="https://likelionhsu.oopy.io/">
                <button>멋쟁이사자처럼 더 알아보기</button>
            </a>
        </div>
        
        <!-- 만든 이들 페이지 -->
        <div id="creator-page" style="color:aliceblue">
            <div class="creator" id="de">UI Designer</div>
            <div class="box">
                <div class="creator-box" id="de-box">
                    <img class="creator-img" src="{% static 'img/people/구가영.png' %}">
                    <div class="creator-info" id="de-info">
                        <p class="creator-position">디자인 팀장</p>
                        <p class="creator-name">구가영</p>
                    </div>
                </div>
                <div class="creator-box" id="de-box">
                    <img class="creator-img" src="{% static 'img/people/박혜연.png' %}">
                    <div class="creator-info" id="de-info">
                        <p class="creator-position">디자인 팀원</p>
                        <p class="creator-name">박혜연</p>
                    </div>
                </div>
            </div>

            <div class="creator" id="fe">Frontend</div>
            <div class="box">
                <div class="creator-box" id="fe-box">
                    <img class="creator-img" src="{% static 'img/people/이자민.png' %}">
                    <div class="creator-info">
                        <p class="creator-position">PM, FE</p>
                        <p class="creator-name">이자민</p>
                    </div>
                </div>
                <div class="creator-box" id="fe-box">
                    <img class="creator-img" src="{% static 'img/people/이장혁.png' %}">
                    <div class="creator-info">
                        <p class="creator-position">FE</p>
                        <p class="creator-name">이장혁</p>
                    </div>
                </div>
            </div>
            <div class="box">
                <div class="creator-box" id="fe-box">
                    <img class="creator-img" src="{% static 'img/people/조서영.png' %}">
                    <div class="creator-info">
                        <p class="creator-position">FE</p>
                        <p class="creator-name">조서영</p>
                    </div>
                </div>
                <div class="creator-box" id="fe-box">
                    <img class="creator-img" src="{% static 'img/people/이서연.png' %}">
                    <div class="creator-info">
                        <p class="creator-position">FE</p>
                        <p class="creator-name">이서연</p>
                    </div>
                </div>
            </div>
            <div class="box">
                <div class="creator-box" id="fe-box"> 
                    <img class="creator-img" src="{% static 'img/people/이가현.png' %}">
                    <div class="creator-info">
                        <p class="creator-position">FE</p>
                        <p class="creator-name">이가현</p>
                    </div>
                </div>
                <div class="creator-box" id="fe-box">
                    <img class="creator-img" src="{% static 'img/people/김지원.png' %}">
                    <div class="creator-info">
                        <p class="creator-position">FE</p>
                        <p class="creator-name">김지원</p>
                    </div>
                </div>
            </div>
            <div class="box">
                <div class="creator-box" id="fe-box">
                    <img class="creator-img" src="{% static 'img/people/임승빈.png' %}">
                    <div class="creator-info">
                        <p class="creator-position">FE</p>
                        <p class="creator-name">임승빈</p>
                    </div>
                </div>
                <div class="creator-box" id="fe-box" style="background-color: transparent;">
                    <!-- <img class="creator-img" src="./people/임승빈.png">
                    <div class="creator-info">
                        <p class="creator-position">FE</p>
                        <p class="creator-name">임승빈</p>
                    </div> -->
                </div>
            </div>
            <div class="creator" id="be">Backend</div>
            <div class="box">
                <div class="creator-box" id="be-box">
                    <img class="creator-img" src="{% static 'img/people/이현승.png' %}">
                    <div class="creator-info">
                        <p class="creator-position">BE</p>
                        <p class="creator-name">이현승</p>
                    </div>
                </div>
                <div class="creator-box" id="be-box">
                    <img class="creator-img" src="{% static 'img/people/양종욱.png' %}">
                    <div class="creator-info">
                        <p class="creator-position">BE</p>
                        <p class="creator-name">양종욱</p>
                    </div>
                </div>
            </div>
            <div class="inspired">
                Designed inspired by 총학생회 '이음'
            </div>
        </div>
        <footer style="background-color: #151937;">
            <p style="color: #92AAFFCC; font-weight: 700;">Contact</p>
            <div style="margin-top: 9px;">
                <p>Instagram</p>
                <p>@likelion_hansung</p>
            </div>
            <div style="margin-top: 6px;">
                <p>Kakaotalk</p>
                <p>한성대학교 멋쟁이사자처럼</p>
            </div>
        </footer>
    </div>
    <script type="text/javascript" src="{% static 'js/aboutus.js' %}"></script> 
    <script type="text/javascript" src="{% static 'js/data.js' %}"></script> 
</body>
</html>

BlueFlame/FestivalApp/templates/booth(Day1).html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/default.css' %}">
    <link rel="stylesheet" href="{% static 'css/booth.css' %}">
    <title>부스</title>
</head>

<body onload="first1()">
    <nav class="navbar fixed-top">
        <input type="checkbox" id="icon">
    <label for="icon">  <!--label은 인라인 스타일-->
        <span></span>
        <span></span>
        <span></span>
    </label>
    <div id="header">
        <img src="{% static 'img/Menu.png' %}" style="height: 3vh; margin-top: 27px; margin-left: 30px;" >
        <div class="line"></div>
        <ul class="menu_item" style="margin-left: 30px;">
            <li>
                <img src="{% static 'img/Vector.png' %}" style="height: 1.5vh;">
                <a href="{% url 'timeline' %}">타임 테이블</a>
            </li>
            <li>
                <img src="{% static 'img/Vector.png' %}" style="height: 1.5vh;">
                <a href="{% url 'booth' 0 %}">부스 안내</a>
            </li>
            <li>
                <img src="{% static 'img/Vector.png' %}" style="height: 1.5vh;">
                <a href="{% url 'aboutus' %}">About us</a>
            </li>
            <li class="menu_li">
                <img src="{% static 'img/Vector.png' %}" style="height: 1.5vh;">
                <a href="{% url 'home' %}">Home</a>
            </li>
        </ul>
    </div>
    </nav>
    <nav id="first-tap-wrap">
        <div id="first-tap1" onclick="first1()">
            <span id="first-time">Day 1</span>
            <br>
            <span id="day1-info">05.10</span>
        </div>

        <div id="first-tap2" onclick="location.href='{% url 'booth' 1 %}'">
            <span id="second-time">Day 2</span>
            <br>
            <span id="day2-info">05.11</span>
        </div>

        <div id="first-tap3" onclick="location.href='{% url 'booth' 2 %}'">
            <span id="third-time">Day 3</span>
            <br>
            <span id="day3-info">05.12</span>
        </div>
    </nav>

    <div class="second-tap" id="day1-wrap" onload="first1()">
        <nav class="second-nav">
            <div class="loc1" id="location1" onclick="first1()">
                <span class="loc1-text" id="location1-text">모두보기</span>
            </div>
            <div class="loc2" id="location2" onclick="first2()">
                <span class="loc2-text" id="location2-text">이벤트 부스</span>
            </div>
            <div class="loc3" id="location3" onclick="first3()">
                <span class="loc3-text" id="location3-text">먹거리 장터</span>
            </div>
        </nav>

        <!-- 모두보기 세부-->
        <div id="loc1-wrap">
            <!-- for문 써야할 부분 -->
            {% for pub in pubs %}
                {% if pub.distinct == 0 %}
                    <div class="location-sector-wrap">
                        <div class="location-sector1">
                            <a href="{% url 'pub' pub.id %}">
                                <p><img class="img" src="{{pub.image.url}}"></p>
                            </a>
                            <p class="major" id="major1">{{pub.belong}}</p>
                            <p class="sub">{{pub.name}}</p>
                            <p class="tag-container">
                                <span class="place">{{pub.location}}</span>
                            </p>
                        </div>
                {% else %}
                        <div class="location-sector2">
                            <a href="{% url 'pub' pub.id %}">
                                <p><img class="img" src="{{pub.image.url}}"></p>
                            </a>
                            <p class="major" id="major1">{{pub.belong}}</p>
                            <p class="sub">{{pub.name}}</p>
                            <p class="tag-container">
                                <span class="place">{{pub.location}}</span>
                            </p>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
            {% for club in clubs %}
                {% if club.distinct == 0 %}
                    <div class="location-sector-wrap">
                        <div class="location-sector1">
                            <a href="{% url 'club' club.id %}">
                                <p><img class="img" src="{{club.image.url}}"></p>
                            </a>
                            <p class="major">{{club.belong}}</p>
                            <p class="sub">{{club.name}}</p>
                            <p class="tag-container">
                                <span class="place">{{club.location}}</span>
                            </p>
                        </div>
                {% else %}
                        <div class="location-sector2">
                            <a href="{% url 'club' club.id %}">
                                <p><img class="img" src="{{club.image.url}}"></p>
                            </a>
                            <p class="major">{{club.belong}}</p>
                            <p class="sub">{{club.name}}</p>
                            <p class="tag-container">
                                <span class="place">{{club.location}}</span>
                            </p>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
            <!-- 여기까지 -->
        </div>

        <!-- 이벤트 부스 세부-->
        <div id="loc2-wrap">
            {% for club in clubs %}
                {% if club.distinct == 0 %}
                    <div class="location-sector-wrap">
                        <div class="location-sector1">
                            <a href="{% url 'club' club.id %}">
                                <p><img class="img" src="{{club.image.url}}"></p>
                            </a>
                            <p class="major">{{club.belong}}</p>
                            <p class="sub">{{club.name}}</p>
                            <p class="tag-container">
                                <span class="place">{{club.location}}</span>
                            </p>
                        </div>
                {% else %}
                        <div class="location-sector2">
                            <a href="{% url 'club' club.id %}">
                                <p><img class="img" src="{{club.image.url}}"></p>
                            </a>
                            <p class="major">{{club.belong}}</p>
                            <p class="sub">{{club.name}}</p>
                            <p class="tag-container">
                                <span class="place">{{club.location}}</span>
                            </p>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>

        <!-- 먹거리 장터 세부 -->
        <div id="loc3-wrap">
            {% for pub in pubs %}
                {% if pub.distinct == 0 %}
                    <div class="location-sector-wrap">
                        <div class="location-sector1">
                            <a href="{% url 'pub' pub.id %}">
                                <p><img class="img" src="{{pub.image.url}}"></p>
                            </a>
                            <p class="major" id="major1">{{pub.belong}}</p>
                            <p class="sub">{{pub.name}}</p>
                            <p class="tag-container">
                                <span class="place">{{pub.location}}</span>
                            </p>
                        </div>
                {% else %}
                        <div class="location-sector2">
                            <a href="{% url 'pub' pub.id %}">
                                <p><img class="img" src="{{pub.image.url}}"></p>
                            </a>
                            <p class="major" id="major1">{{pub.belong}}</p>
                            <p class="sub">{{pub.name}}</p>
                            <p class="tag-container">
                                <span class="place">{{pub.location}}</span>
                            </p>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>

        <footer style="background-color: #151937;">
            <p style="color: #92AAFFCC; font-weight: 700;">Contact</p>
            <div style="margin-top: 9px;">
                <p>Instagram</p>
                <p>@likelion_hansung</p>
            </div>
            <div style="margin-top: 6px;">
                <p>Kakaotalk</p>
                <p>한성대학교 멋쟁이사자처럼</p>
            </div>
        </footer>
        <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
        <script type="text/javascript" src="{% static 'js/booth.js' %}"></script>
</body>

BlueFlame/FestivalApp/templates/booth.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/default.css' %}">
    <link rel="stylesheet" href="{% static 'css/booth.css' %}">
    <title>Document</title>
</head>
<body>
    부스
</body>
</html>

BlueFlame/FestivalApp/templates/club.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/default.css' %}">
    <link rel="stylesheet" href="{% static 'css/booth2.css' %}">
    <title>{{club.name}}</title>
</head>

<body class="div1">
    <button class="button" type="button" onclick="myFunction()">
        <img class="back-image" src="{% static 'img/back.png' %}" alt="back_button">
    </button>

    <script>
        function myFunction() {
          // booth.html로 이동
            window.location.href = "booth.html";
        }
    </script>
    <img src="{% static 'img/LogoText.png' %}" alt="BlueFlame" class="logo" >
    <nav class="navbar fixed-top">
        <input type="checkbox" id="icon">
    <label for="icon">  <!--label은 인라인 스타일-->
        <span></span>
        <span></span>
        <span></span>
    </label>
    <div id="header">
        <img src="{% static 'img/Menu.png' %}" style="height: 3vh; margin-top: 27px; margin-left: 30px;" >
        <div class="line"></div>
        <ul class="menu_item" style="margin-left: 30px;">
            <li> 
                <img src="{% static 'img/Vector.png' %}" style="height: 1.5vh;">
                <a href="{% url 'timeline' %}">타임 테이블</a>
            </li>
            <li class="menu_li">
                <img src="{% static 'img/Vector.png' %}" style="height: 1.5vh;">
                <a href="{% url 'booth' 0 %}">부스 안내</a> 
            </li>
            <li class="menu_li">
                <img src="{% static 'img/Vector.png' %}" style="height: 1.5vh;">
                <a href="{% url 'aboutus' %}">About us</a>
            </li>
            <li class="menu_li">
                <img src="{% static 'img/Vector.png' %}" style="height: 1.5vh;">
                <a href="{% url 'home' %}">Home</a>
            </li>
        </ul>
    </div>
    </nav>
    <div class="title">
        <p class="track-text">{{club.belong}}</p>
        <p class="drink-text">{{club.name}}</p>
        <img class ="image" src="{{club.image.url}}" alt="이미지 설명">
        <div class="upper-section">
            <p class="ss-text">
                {{club.content}}
            </p>
        </div>
        <div class="lower-section">
            <p class="ss-text">
                {{club.information}}
            </p>
        </div>
    </div>
    <div class="upper-section">
        <p class="INSTA">
            CONTACT : {{club.contact}}
        </p>
    </div>

    <div class="lower-section">
        <div class="div3">
            <p class="place-title">장소</p>
            <p class="place">{{club.location}}</p>
        </div>
        <img class ="image-place" src="{% static 'img/booth12.png' %}" alt="">
    </div>
    
</body>

<footer style="background-color: #151937;">
    <p style="color: #92AAFFCC; font-weight: 700;">Contact</p>
    <div style="margin-top: 9px;">
        <p>Instagram</p>
        <p>@likelion_hansung</p>
    </div>
    <div style="margin-top: 6px;">
        <p>Kakaotalk</p>
        <p>한성대학교 멋쟁이사자처럼</p>
    </div>
</footer>
</html>

BlueFlame/FestivalApp/templates/pub.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/default.css' %}">
    <link rel="stylesheet" href="{% static 'css/booth2.css' %}">
    <title>{{pub.name}}</title>
</head>

<body class="div1">
    <button class="button" type="button" onclick="myFunction()">
        <img class="back-image" src="{% static 'img/back.png' %}" alt="back_button">
    </button>

    <script>
        function myFunction() {
          // booth.html로 이동
            window.location.href = "booth.html";
        }
    </script>
    <img src="{% static 'img/LogoText.png' %}" alt="BlueFlame" class="logo" >
    <nav class="navbar fixed-top">
        <input type="checkbox" id="icon">
    <label for="icon">  <!--label은 인라인 스타일-->
        <span></span>
        <span></span>
        <span></span>
    </label>
    <div id="header">
        <img src="{% static 'img/Menu.png' %}" style="height: 3vh; margin-top: 27px; margin-left: 30px;" >
        <div class="line"></div>
        <ul class="menu_item" style="margin-left: 30px;">
            <li> 
                <img src="{% static 'img/Vector.png' %}" style="height: 1.5vh;">
                <a href="{% url 'timeline' %}">타임 테이블</a>
            </li>
            <li class="menu_li">
                <img src="{% static 'img/Vector.png' %}" style="height: 1.5vh;">
                <a href="{% url 'booth' 0 %}">부스 안내</a> 
            </li>
            <li class="menu_li">
                <img src="{% static 'img/Vector.png' %}" style="height: 1.5vh;">
                <a href="{% url 'aboutus' %}">About us</a>
            </li>
            <li class="menu_li">
                <img src="{% static 'img/Vector.png' %}" style="height: 1.5vh;">
                <a href="{% url 'home' %}">Home</a>
            </li>
        </ul>
    </div>
    </nav>
    <div class="title">
        <p class="track-text">{{pub.belong}}</p>
        <p class="drink-text">{{pub.name}}</p>
        {% comment %} <img class ="image" src="{{pub.image.url}}" alt="이미지 설명"> {% endcomment %}
        <div class="upper-section">
            <p class="ss-text">
                {{pub.content}}
            </p>
        </div>
        <div class="lower-section">
            <p class="INSTA">
            CONTACT : {{pub.contact}}
            </p>
        </div>
    </div>
    <div class="upper-section">
        <p class="menu-text">메뉴</p>
            {%for menu in pub.menu_set.all%}
                <div class="div2">
                    <p class="l1-menu">{{menu.name}}</p>
                    <hr class="line-menu">
                    <p class="r1-menu"> {{menu.price}}</p>
                </div>
            {%endfor%}
    </div>

    <div class="lower-section">
        <div class="div3">
            <p class="place-title">장소</p>
            <p class="place">{{pub.location}}</p>
        </div>
        <img class ="image-place" src="{% static 'img/booth12.png' %}" alt="">
    </div>
    
</body>

<footer style="background-color: #151937;">
    <p style="color: #92AAFFCC; font-weight: 700;">Contact</p>
    <div style="margin-top: 9px;">
        <p>Instagram</p>
        <p>@likelion_hansung</p>
    </div>
    <div style="margin-top: 6px;">
        <p>Kakaotalk</p>
        <p>한성대학교 멋쟁이사자처럼</p>
    </div>
</footer>
</html>